### BUILD THE FRONTEND

# the React front end
FROM node:16-alpine as stage_1

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH
COPY package.json yarn.lock ./
COPY ./src ./src
COPY ./public ./public
RUN yarn install
RUN yarn build

# an nginx container
FROM nginx:stable-alpine as movieme_client

COPY --from=frontend-stage /app/build /usr/share/nginx/html
COPY deployment/nginx.default.conf /etc/nginx/conf/default.conf
