version: "3.9"
services:
  movieme_api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: movieme_api
  movieme_client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: movieme_client
    ports:
      - "3000:80"
